### ISSUE TITLE
problem linking android version of a game

### ISSUE THREAD

**Issue by nanocore** [NatWeiss/RapidGame#15] opened 2015-06-13 21:18 UTC
I am trying to build an android version of my app on OSX. I have installed the android sdk and android ndk (9) from homebrew ( and updated ANDROID_SDK_ROOT and NDK_ROOT to point to these new SDK locations) and upgraded to 0.9.9 for rapidgame and did a prebuild. That built successfully. Also, did a remove lib and rapidgame init . in the main directory. My app compiles cleanly for iOS and OSX, and am on to android. Granted this is my first time compiling an android app, and searched the internet for most of the issues that I have come across so far. I saw the note in the issues log about including cocos_zlib_static so that problem is gone. I am down to the last one. The process is at the linking stage and it can't resolve getPositionPercent(). I went down the path of including cocos_ui_static which then wanted 10 more static libs before asking for cocos_ui_static again. So, I stopped there. My Android.mk linking flags and static lib definitions looks like:
LOCAL_LDFLAGS := -Wl,—allow-multiple-definition
LOCAL_WHOLE_STATIC_LIBRARIES := libcocos2dx-prebuilt
LOCAL_WHOLE_STATIC_LIBRARIES += cocospngstatic cocosjpegstatic cocostiffstatic cocoswebpstatic \
cocoscurlstatic cocosfreetype2static spidermonkeystatic websocketsstatic cocoschipmunkstatic \
cocoszlibstatic
and the linking output:

ARCH=armeabi
APP_CPPFLAGS=-frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DCOCOS2D_JAVASCRIPT -DCOCOS2D_DEBUG=1
make[1]: Entering directory `/Users/...projectinfohere.../Projects/android'
[armeabi] Compile++ thumb: cocos2djs_shared <= main.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= AppDelegate.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= Game.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= GameScene.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= MenuScene.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= AdminLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= BallsLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= BorderLevelLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= Level.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= OverlayLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= RotatorItem.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= HighScoreLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= RotatorLayer.cpp
[armeabi] SharedLibrary  : libcocos2djs.so
jni/../../../lib/cocos2d/x/lib/Debug-Android/armeabi/libcocos2dx-prebuilt.a(CCNodeReader.o):CCNodeReader.cpp:function cocostudio::timeline::NodeReader::loadNode(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&): error: undefined reference to 'cocos2d::ui::Widget::getPositionPercent() const'
jni/../../../lib/cocos2d/x/lib/Debug-Android/armeabi/libcocos2dx-prebuilt.a(CCNodeReader.o):CCNodeReader.cpp:function cocostudio::timeline::NodeReader::loadNode(rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> > const&): error: undefined reference to 'cocos2d::ui::Widget::getPositionPercent() const'
collect2: error: ld returned 1 exit status
Any thoughts?

**Comment by samoersnaes** [comment] 2015-06-13 21:46
Hi nanocore.

Just to be clear, you tried something like [this](http://discuss.cocos2d-x.org/t/solved-eclipse-adt-compilation-problem/16818/2), right? Just for more information as I don't have access to a Mac (although in principle it should work the same on Windows), could I ask you to compile again with cocos_ui_static included and send me the output?

**Comment by nanocore** [comment] 2015-06-13 22:07
Yes, I did. but here is the output with cocos_ui_static and the call import-module,ui added:

CONFIG=Debug
ARCH=armeabi
APP_CPPFLAGS=-frtti -DCC_ENABLE_CHIPMUNK_INTEGRATION=1 -std=c++11 -fsigned-char -DCOCOS2D_JAVASCRIPT -DCOCOS2D_DEBUG=1
make[1]: Entering directory `/Users/greggjensen/dev/RotatEm/Projects/android'
[armeabi] Compile++ thumb: cocos2djs_shared <= main.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= AppDelegate.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= Game.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= GameScene.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= MenuScene.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= AdminLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= BallsLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= BorderLevelLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= Level.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= OverlayLayer.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= RotatorItem.cpp
[armeabi] Compile++ thumb: cocos2djs_shared <= HighScoreLayer.cpp
make[1]: *** No rule to make target `/Users/greggjensen/dev/RotatEm/Projects/android/../../lib/cocos2d/x/java/mk/cocos2d-x/extensions/assets-manager/AssetsManager.cpp', needed by `obj/local/armeabi/objs-debug/cocos_extension_static/assets-manager/AssetsManager.o'.  Stop.
make[1]: *** Waiting for unfinished jobs....

And this is what I was mentioning before that I then add cocos_extensions_static which then wants something else which then wants something else...  until it comes back around to wanting cocos_ui_static again.  

Appreciate the help!  I have 2 other much bigger projects coming very soon, so I need to understand this process so that it goes a bit smoother for those.  Hence, my start on something small.  And I may run into a bigger problem after I get this compiled as I don't have a physical android device and will be trying the emulator in (I assume) the android studio.  So, as a tangent I would be interested in suggestions about a physical device for testing.  This project is targeted at the phones (ie, smaller playing field).

**Comment by samoersnaes** [comment] 2015-06-13 22:34
1. Have you made absolutely sure you are doing a clean build (`make clean && make`)?

2. Well, it seems maybe the template Android.mk isn't sufficient for your needs. It could be that you need to do the same thing for the rest of the static libraries that you rely on as you did for cocos_ui_static. Maybe only including all of them will silence the errors for each of them individually. See [this](http://discuss.cocos2d-x.org/t/solved-eclipse-adt-compilation-problem/16818/8) for example. Basically, try adding all the "something elses" and see if that works.

3. The Android emulator is extremely slow. You should definitely find someone with an Android phone who's willing to test your game. I would gladly volunteer (I have an [LG G3](http://www.gsmarena.com/lg_g3-6294.php)) after exams are over next week for me.

4. Tangential question: I've recently added a script that will automatically update your C/C++ source files in Android.mk based on the changes you make in Projects/. This update occurs each time you run `make`, and there is an ignore file where you can list files you wish to exclude from the Android-specific build. Do you think that might be useful so you don't need to fiddle with Android.mk every time you create or delete a source file?

**Comment by nanocore** [comment] 2015-06-13 22:49
1. Yes, many times ;-)
2.  I have done this a couple of times too, but I haven't started with the libcocos2d-prebuilt and add from there. Actually, what things make up that prebuilt library?
3. Once I get over this hurdle I may take you up in that. 
4. I think it would have helped the very first time I tried to build as u thought that it would already do that. So, I had to find the android.mk and update it manually.   So yes this will help, but probably won't address my specific issue. 


My iPhone sent this ...

**Comment by samoersnaes** [comment] 2015-06-13 23:07
1 (4). Yeah, that's why it was tangential. I just wanted to make sure someone else thought it was useful, as it's going in the next release.

2 (2). You can see what gets built by going to rapidgame/src/proj.android/build.sh. RapidGame is stored in two different places on Mac I believe: `~/Library/Developer/RapidGame` and `/usr/local/lib/node_modules/rapidgame`, so if you don't find a `src` folder in one place, try the other. At the bottom of the build script you'll see what goes into cocos2d-x. I checked and there's nothing missing from the prebuilt library, as the purpose is to prebuild cocos2d-x in its entirety.

3. One more thing. This is a cocos2d-x project and not cocos2d-js, right? I'm 99.9% certain for various reasons that you're project is cocos2d-x and not JS, but I want to remove any ambiguity about that.

4. Holy crap. I just may have found an error in build.sh! It's related to the JS bindings though, so nothing to do with your particular problem.

5. Could I bother you to include all the missing static libraries (the relevant ones) and send me the output of the build again?

**Comment by samoersnaes** [comment] 2015-06-14 10:20
SOLUTION BELOW

First off, sorry for the small mistakes and any unclear language from yesterday. It was late here :) Anyway, I tried to build a project myself after adding cocos_ui_static to Android.mk, and found out like you did that you go down a dependency rabbit hole. Obviously, everything you need should be in the prebuilt library. So I tracked down the files and functions/methods referred to in your original error. It turns out I can't find `CCNodeReader.cpp`. It should be stored in `rapidgame/src/cocos2d-js/frameworks/js-bindings/cocos2d-x/cocos/editor-support/cocostudio/ActionTimeline/CCNodeReader.cpp`, but it's not there. I checked the cocos2d-x [Github page](https://github.com/cocos2d/cocos2d-x) and searched for the file in the folder where the [v.3.4 reference](http://www.cocos2d-x.org/reference/native-cpp/V3.4/d0/d17/_c_c_node_reader_8h.html) says it should be. My only conclusion can be that CCNodeReader was removed between v3.4 and v3.6. Browsing through their [releases](https://github.com/cocos2d/cocos2d-x/releases) proves this. I checked [3.5](https://github.com/cocos2d/cocos2d-x/tree/f7e11a2467e4508738ad9cf4b3992da05f9d1e7c/cocos/editor-support/cocostudio/ActionTimeline) as well and found CCNodeReader was still there.

Ta-da! So, the question shouldn't be why doesn't your Android project compile, but rather why your Mac and iOS projects do. Your source code must rely on CCNodeReader somewhere, so the problem lies with the fact that your project now links to the v3.6 library. The way to fix everything in a way that takes the least mental effort would be to muck around with the library version that gets downloaded by RapidGame, and then prebuild all the libraries again. Of course, this will take a lot of time on your computer, but alternatively you could figure out how to replace your deprecated code so it is compliant with 3.6. If you want to know how to do the former option, here are the steps:

DISCLAIMER

I'm assuming this is the first time you have updated RapidGame in a while, meaning when you created your project, you were linking to cocos2d-x-3.2 (RapidGame 0.9.2 to 0.9.5). It might therefore be safer to download v3.2 instead of 3.5, as there may be additional deprecated Cocos API calls that your code relies on.

1. Find `rapidgame.js` in one of the two directories I mentioned earlier and open it in a text editor.
2. On lines 33 and 34, change the bits on the end from `cocos2d-js-v3.6.zip` to `cocos2d-js-v3.5.zip`.
3. Save and close.
4. Delete the `latest` symlink and the `0.9.9` folder.
5. Change to any directory you want, as you are going to create a dummy project.
6. Run `rapidgame create cocos2dx "TestProj" com.comp.testproj`. The reason I'm having you create a dummy project is that RapidGame does a little more stuff when you create a "first project" versus when you run `rapidgame prebuild`.
7. Wait for RapidGame to prebuild cocos2d-x-3.5.
8. Delete the dummy project and remove the `lib` symlink in your actual project and run `rapidgame init` in the directory.
9. Your project should now compile for every platform.

Based on the above info--the fact that the problem isn't with RapidGame--I consider the issue solved :) However, I'll wait until you reply with any comments/questions, or just letting me know if you're satisfied with the two potential solutions. You can close the issue yourself when you read this, otherwise I will wait until I get a response that you're happy with the solution before I close the issue.

**Comment by nanocore** [comment] 2015-06-14 14:19
OMG!! You went way overboard, I am so very appreciative!!!  You described my environment to a tee.   I did start with rapid game 9.3 and went up to 9.5.  In this process I removed these old builds and brought down 9.9. But did NOT recreate the game's directory. Just did the remove lib and did the rapidgame init. The interesting part is that I don't know that the cocos2dx library actually rebuilt during the rebuild stage as it went to success way to quickly. Looking at the log I didn't see the files being complied just the library being built. I assumed that was correct. I need to do what you have said and probably remove everything that rapidgame has built and see if my iOS project still builds. I bet it does. It is probably getting it from some place that need to find and remove. Then start over. I can pull my sources out and even rebuild the project. Is the update in rapidgame to automatically put the sources in the Android.mk ? Not that I have that many files but it sets an expectation for me. 

Again thanks for the Help, I think this is on the right track. 


My iPhone sent this ...

**Closed** 2015-06-14 14:21 UTC

**Comment by samoersnaes** [comment] 2015-06-14 14:58
Numbered list again to sort my thoughts :)

1. You're spot on about the build log. Some of the libraries at least are only being linked together from the already compiled object files. The actual time it should take to prebuild cocos2d-x for every possible arch and config should take around 2 hours.

2. You don't need to recreate the game's directory at all. After the proper libraries are prebuilt, all you need to do to update your project is exactly as you described: `cd $MyGameDir && rm lib && rapidgame init .`

3. Yes, just nuke everything related to rapidgame (node has an uninstall command, but you have to be in the right directory, so just make sure everything in `~/Library/Developer/RapidGame` and `/usr/local/lib/node_modules/rapidgame` gets deleted) and do a fresh install. Then make the changes to `rapidgame.js` such that RapidGame will download the source files for cocos2d-x-3.x (whatever version you think is best, from 3.2 to 3.5). Then create a new project somewhere, which will cause RapidGame to create `0.9.9` and `latest` and prebuild the libraries for the version you specified at the top `rapidgame.js`. For clarity, RapidGame downloads cocos2d-js, which is built on top of cocos2d-x and therefore includes everything you need.

4. After that, your project should compile on EVERY platform. The way you describe the current state of the libraries on your computer is a bit confusing, but my understanding is that somehow your Mac and iOS project are linking to the 3.2 libraries, and somehow Android's libraries were updated to 3.6. You can find the library archive files themselves in `rapidgame/0.9.9/cocos2d/x/lib/[PLATFORM]`.

5. I don't know when we'll release the next version, but you can get all the main functionality right now by adding `README.html` (recently updated and especially meant for those unfamiliar with Android), `build_files.py`, `makefile` and `makeignore` from [here](https://github.com/NatWeiss/RapidGame/tree/master/templates/cocos2dx/TwoScene/Projects/android) into your `Projects/android/` directory, and then every time you run `make`, your C and C++ files  in `Projects` will be updated in `LOCAL_SRC_FILES` in `Projects/android/jni/Android.mk`.

6. You should have noticed that when the Android libraries are prebuilt, RapidGame outputs "Prebuilding Android undefined..." As assurance, nothing is going wrong, but the string to output wasn't set correctly in v0.9.9 and has already been fixed.

Hit me up with more questions and progress (!), cause I'm interested in hearing how it goes and I want to make sure everything works on your end, even though the issue is closed.

**Comment by nanocore** [comment] 2015-06-15 00:52
I removed everything in ~/Library/Developer/RapidGame and changed rapidgames.js to download 3.5.  Before the build started, there were several errors about not being able to apply patches:

exec error: Error: Command failed: error: patch failed: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.cpp:138
error: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.cpp: patch does not apply
error: patch failed: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.h:76
error: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.h: patch does not apply


error: patch failed: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.cpp:138
error: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.cpp: patch does not apply
error: patch failed: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.h:76
error: frameworks/js-bindings/cocos2d-x/cocos/renderer/CCGLProgramState.h: patch does not apply

Probably OK, so continuing and the build appears to be succeeding.   Will respond to this thread after the android build of my app.

**Comment by nanocore** [comment] 2015-06-15 02:01
Progress!  Built cocos2dx 3.5 and then iOS and Mac versions with no problem.  And, the android verison got past the previous linking issue!!!  Now, I have some research to do to understand the build targets as I am taking the defaults, and the latest issue seems to be with it.  The error is:

ant -Dsdk.dir=/usr/local/opt/android-sdk -Dplugin.dir=$(cd ../../lib/cocos2d/x/java && pwd) debug
Buildfile: /Users/...projectinfohere.../Projects/android/build.xml

-set-mode-check:

-set-debug-files:

-check-env:
 [checkenv] Android SDK Tools Revision 24.3.2
 [checkenv] Installed at /usr/local/opt/android-sdk

-setup:
     [echo] Project Name: ...ProjectInfoHere....
  [gettype] Project Type: Application

-set-debug-mode:

-debug-obfuscation-check:

-pre-build:

-build-setup:
[getbuildtools] Using latest Build Tools: 22.0.1
     [echo] Resolving Build Target for ...ProjectInfoHere...

BUILD FAILED
/usr/local/opt/android-sdk/tools/ant/build.xml:538: Unable to resolve project target 'android-18'

Total time: 0 seconds
make: *** [all] Error 1

**Comment by nanocore** [comment] 2015-06-15 03:08
I resolved this by adding the API build 18 (and then API build 10 that it wanted after that).  Then I stumbled over the build.xml file not have the correct tools location.  The error was:/usr/local/opt/android-sdk/tools/ant/build.xml:694: Execute failed: java.io.IOException: Cannot run program "/Users/greggjensen/Library/Developer/RapidGame/0.9.9/cocos2d/x/java/cocos2d-x/${aapt}" (in directory "/Users/greggjensen/Library/Developer/RapidGame/0.9.9/cocos2d/x/java/cocos2d-x"): error=2, No such file or directory

This was solved by changing the tools section in: /usr/local/opt/android-sdk/tools/ant/build.xml

with the following:    
    <property name="android.tools.dir" location="${sdk.dir}/tools" />
    <property name="android.platform.tools.dir" location="${sdk.dir}/platform-tools" />
    <property name="android.buildtools.dir" location="${sdk.dir}/build-tools/22.0.1" />
    <condition property="exe" value=".exe" else=""><os family="windows" /></condition>
    <condition property="bat" value=".bat" else=""><os family="windows" /></condition>
    <property name="adb" location="${android.platform.tools.dir}/adb${exe}" />
    <property name="lint" location="${android.tools.dir}/lint${bat}" />
    <property name="zipalign" location="${android.buildtools.dir}/zipalign${exe}" />
    <property name="aidl" location="${android.platform.tools.dir}/aidl${exe}" />
    <property name="aapt" location="${android.buildtools.dir}/aapt${exe}" />
    <property name="dx" location="${android.buildtools.dir}/dx${bat}" />
    <property name="renderscript" location="${android.buildtools.dir}/llvm-rs-cc${exe}"/>
    <property name="lint" location="${android.tools.dir}/lint${bat}" />

Next is to actually get it to run...

**Comment by samoersnaes** [comment] 2015-06-15 03:35
Oh no! Did you read the [Android README](http://htmlpreview.github.io/?https://github.com/NatWeiss/RapidGame/blob/master/templates/cocos2dx/TwoScene/Projects/android/README.html) I had linked you to? Maybe I should've accented it more, as the Android API problem and the build tools problem could've both been resolved by taking a look at it. The main thing I think you're missing is setting up all the environment variables. But take a look! If you can't find the answers in the README, let me know.

**Comment by samoersnaes** [comment] 2015-06-15 04:03
After setting your environment variables, you shouldn't need to edit the `build.xml` file, so you can revert the changes you made in it to see for yourself. After going through the slightly annoying but necessary setup laid out in the README (these things are simply required for Android development and outside of RapidGame's automation scope), you won't need to touch anything for future projects, meaning you can create a new template project and just say `make` and it works. Also, I believe the reason you got those errors about failed patches is because Nathanael had modified the cocos2d-x sources a bit and set those changes in `rapidgame/src/cocos2d.patch`. These modifications were of course intended to be applied to the cocos version that RapidGame downloads (3.6). But it appears everything still went fine on that front for you :)

If you go back and check the [README](https://github.com/NatWeiss/RapidGame) for RapidGame, you'll see that we link to the Android README in the requirements near the top, but I guess its placement is more geared toward someone installing RapidGame for the first time and not someone updated their version. I just hope that's the case at least, because we want as many people as possible who are interested in Android development to read through that README as well.

**Comment by nanocore** [comment] 2015-06-15 14:56
Yes I had read that README a couple of times but maybe I was just focused away from what it tried to say to get it. In the end I have a successful build, but haven't run it I am android environment yet.  I bet the next project will be easier.  Thanks for all your help!


My iPhone sent this ...

**Comment by samoersnaes** [comment] 2015-06-15 16:19
Thanks and good luck!

P.S. If you create an emulator in AVD Manager (you'll want to create an ARM device of course for several reasons), you can do `make start-emulator` and `make run-emulator` in a new shell after that and at the very least see if your app launches successfully. If you have an .apk and want to see if it runs on a physical Android device and are comfortable with it, send me an email (you can find my address on my [Github page](https://github.com/samoersnaes)).

Otherwise good luck again and hope the next project goes smoother! Let us know if any future issues pop up.
